service:
  name: greenlabs-inbound

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x # latest nodejs runtime available in lambda
  region: ap-northeast-2 # can be adjusted to a region closer to you
  iam:
    role: arn:aws:iam::887960154422:role/market-price-service-lambda-role

functions:
  hello:
    memorySize: 512
    timeout: 900
    handler: index.serviceDBJobHandler    
    events:
      - http:
          method: post
          path: hello/post
    environment:
      SERVERLESS_EXPRESS_PLATFORM: aws
